### ISSUE TITLE
LetsEncrypt Compatibility

### ISSUE THREAD

**Issue by sschadwick** [JensDebergh/certificate-dashboard#2]
Doesn't seem to work for my LE-generated certs

**Comment by thinkswan** [comment]
@sschadwick Good catch! The Let's Encrypt certificate authority has an apostrophe in their name, but the data is not being escaped in the HTML, hence the error.

This is fixed in #4, so your LE certs should start being displayed correctly as soon as @JensDebergh has a chance to merge the fix. 🙌
